// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct C2S_EXTEND_SESSION : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static C2S_EXTEND_SESSION GetRootAsC2S_EXTEND_SESSION(ByteBuffer _bb) { return GetRootAsC2S_EXTEND_SESSION(_bb, new C2S_EXTEND_SESSION()); }
  public static C2S_EXTEND_SESSION GetRootAsC2S_EXTEND_SESSION(ByteBuffer _bb, C2S_EXTEND_SESSION obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C2S_EXTEND_SESSION __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string NickName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNickNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNickNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNickNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<C2S_EXTEND_SESSION> CreateC2S_EXTEND_SESSION(FlatBufferBuilder builder,
      StringOffset nick_nameOffset = default(StringOffset)) {
    builder.StartTable(1);
    C2S_EXTEND_SESSION.AddNickName(builder, nick_nameOffset);
    return C2S_EXTEND_SESSION.EndC2S_EXTEND_SESSION(builder);
  }

  public static void StartC2S_EXTEND_SESSION(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddNickName(FlatBufferBuilder builder, StringOffset nickNameOffset) { builder.AddOffset(0, nickNameOffset.Value, 0); }
  public static Offset<C2S_EXTEND_SESSION> EndC2S_EXTEND_SESSION(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<C2S_EXTEND_SESSION>(o);
  }
};

