// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct C2S_REQUEST_REGISTER : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static C2S_REQUEST_REGISTER GetRootAsC2S_REQUEST_REGISTER(ByteBuffer _bb) { return GetRootAsC2S_REQUEST_REGISTER(_bb, new C2S_REQUEST_REGISTER()); }
  public static C2S_REQUEST_REGISTER GetRootAsC2S_REQUEST_REGISTER(ByteBuffer _bb, C2S_REQUEST_REGISTER obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C2S_REQUEST_REGISTER __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Email { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEmailBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetEmailBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetEmailArray() { return __p.__vector_as_array<byte>(4); }
  public string Password { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPasswordBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPasswordArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<C2S_REQUEST_REGISTER> CreateC2S_REQUEST_REGISTER(FlatBufferBuilder builder,
      StringOffset emailOffset = default(StringOffset),
      StringOffset passwordOffset = default(StringOffset)) {
    builder.StartTable(2);
    C2S_REQUEST_REGISTER.AddPassword(builder, passwordOffset);
    C2S_REQUEST_REGISTER.AddEmail(builder, emailOffset);
    return C2S_REQUEST_REGISTER.EndC2S_REQUEST_REGISTER(builder);
  }

  public static void StartC2S_REQUEST_REGISTER(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddEmail(FlatBufferBuilder builder, StringOffset emailOffset) { builder.AddOffset(0, emailOffset.Value, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(1, passwordOffset.Value, 0); }
  public static Offset<C2S_REQUEST_REGISTER> EndC2S_REQUEST_REGISTER(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<C2S_REQUEST_REGISTER>(o);
  }
};

