// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum MESSAGE_ID : byte
{
  NONE = 0,
  S2C_MOVE = 1,
  S2C_SHOOT = 2,
  C2S_MOVE = 3,
};

