// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum MESSAGE_ID : byte
{
  NONE = 0,
  S2C_MOVE = 1,
  S2C_SHOOT = 2,
  C2S_MOVE = 3,
  C2S_EXTEND_SESSION = 4,
  C2S_REQUEST_LOGIN = 5,
  C2S_REQUEST_REGISTER = 6,
  S2C_COMPLETE_LOGIN = 7,
  S2C_COMPLETE_REGISTER = 8,
  S2C_LOGIN_ERROR = 9,
  S2C_REGISTER_ERROR = 10,
  C2S_START_MATCHING = 11,
  S2C_GAME_START = 12,
};

