// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct S2C_PICKUP_GUN : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static S2C_PICKUP_GUN GetRootAsS2C_PICKUP_GUN(ByteBuffer _bb) { return GetRootAsS2C_PICKUP_GUN(_bb, new S2C_PICKUP_GUN()); }
  public static S2C_PICKUP_GUN GetRootAsS2C_PICKUP_GUN(ByteBuffer _bb, S2C_PICKUP_GUN obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S2C_PICKUP_GUN __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Nickname { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNicknameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNicknameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNicknameArray() { return __p.__vector_as_array<byte>(4); }
  public int Gunnum { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<S2C_PICKUP_GUN> CreateS2C_PICKUP_GUN(FlatBufferBuilder builder,
      StringOffset nicknameOffset = default(StringOffset),
      int gunnum = 0) {
    builder.StartTable(2);
    S2C_PICKUP_GUN.AddGunnum(builder, gunnum);
    S2C_PICKUP_GUN.AddNickname(builder, nicknameOffset);
    return S2C_PICKUP_GUN.EndS2C_PICKUP_GUN(builder);
  }

  public static void StartS2C_PICKUP_GUN(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddNickname(FlatBufferBuilder builder, StringOffset nicknameOffset) { builder.AddOffset(0, nicknameOffset.Value, 0); }
  public static void AddGunnum(FlatBufferBuilder builder, int gunnum) { builder.AddInt(1, gunnum, 0); }
  public static Offset<S2C_PICKUP_GUN> EndS2C_PICKUP_GUN(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<S2C_PICKUP_GUN>(o);
  }
};

